### ISSUE TITLE
Removing CSS Package Fails

### ISSUE THREAD

**Issue by garretthyder** [ryboe/CSS3#10]
Hello,
When I attempt to remove the CSS package as suggested:
  Mac:           cmd+shift+p  -> Package Control: Disable Package -> CSS

I get the following error, any thoughts?
Error loading syntax file "Packages/CSS/CSS.tmLanguage": Unable to open Packages/CSS/CSS.tmLanguage

I'm on Sublime Text 3

Thanks

**Comment by FelipeDeCastro** [comment]
I have removed instead of disabling and now I'm always having this messaging "Error loading syntax file "Packages/CSS/CSS.tmLanguage": Unable to open Packages/CSS/CSS.tmLanguage", even if no CSS file is opened. Any suggestion? I can't find the package to install it again...

**Comment by y0ssar1an** [comment]
Your best option is probably to reinstall Sublime. If you can't do that, you can try cloning this repo and copying [this directory](https://github.com/sublimehq/Packages/tree/master/CSS) to your Packages/ directory. That will solve your problem for now, but it won't be updated when Sublime is updated.

**Comment by FelipeDeCastro** [comment]
I've tried to reinstall, but it continues the same. Maybe if I remove this path "Library/Application Support/Sublime Text 3" before the reinstallation? I'm a bit afraid to do so.

**Comment by ehausen** [comment]
Any luck with this? I get this all the time now.
If no CSS files are open, then at least something with inline CSS probably

**Comment by y0ssar1an** [comment]
This package has a serious problem when dealing with syntaxes that have inline CSS, like HTML and PHP. CSS3 loads too many "contexts" (syntax rules) on the stack, and it exceeds a limit set by Sublime Text. When you're editing a pure `.css` file, it will work fine. But when you're editing HTML, PHP, etc., those languages load lots of contexts of their own, then load all the CSS3 contexts. This will frequently exceed the stack limit and [break CSS highlighting with an ugly error message](https://github.com/y0ssar1an/CSS3/issues/107). Unfortunately, there is no simple fix for this. CSS3 needs major streamlining, and I don't have the time for it.

I hate to say it, but CSS3 should not be used for inline CSS. I would recommend using the default CSS package for that. That means you have to enable CSS/disable CSS3 for inline, and disable CSS, enable CSS3 for pure `.css` files. Sorry!
