### ISSUE TITLE
Missing syntax for `background-position-x` & `background-position-y`

### ISSUE THREAD

**Issue by CrazyTim** [ryboe/CSS3#137]
Missing syntax for:
- `background-position-y`
- `background-position-x`

**Comment by ryboe** [comment]
`background-position-x` and `background-position-y` were apparently added in an early draft of [Backgrounds and Borders Module Level 4](https://drafts.csswg.org/css-backgrounds-4/#background-position-longhands). Thanks for the heads up! I'll ship an update soon.

**Comment by ryboe** [comment]
Added in #138.
