### ISSUE TITLE
`-webkit-touch-callout` support?

### ISSUE THREAD

**Issue by argyleink** [ryboe/CSS3#148]
<img width="647" alt="Screen Shot 2021-02-24 at 3 00 58 PM" src="https://user-images.githubusercontent.com/1134620/109077594-42fb8180-76b1-11eb-8c77-b7e32bb432ab.png">

**Comment by vrugtehagel** [comment]
This property is non-standard and actually already on the [bad property list](https://gist.github.com/ryboe/bb95223148e486acbe7a#file-bad_css-L281) so I reckon we shouldn't be adding it.
