### ISSUE TITLE
`@supports` struggles on houdini feature checks

### ISSUE THREAD

**Issue by argyleink** [ryboe/CSS3#152]
<img width="714" alt="Screen Shot 2021-02-24 at 3 11 24 PM" src="https://user-images.githubusercontent.com/1134620/109078817-d2edfb00-76b2-11eb-8694-4737d5a766c9.png">

might just need to add `paint` to the list of props it accepts?

**Comment by ryboe** [comment]
I took a crack at implementing the `paint()` function in [v2.1.37](https://github.com/ryboe/CSS3/releases/tag/v2.1.37). Please let me know if the syntax highlighting is broken or missing anything.

**Comment by argyleink** [comment]
lgtm!
