### ISSUE TITLE
`@supports` highlight bug?

### ISSUE THREAD

**Issue by argyleink** [ryboe/CSS3#153]
Here's it nested and looking especially broken
<img width="590" alt="Screen Shot 2021-02-24 at 3 16 57 PM" src="https://user-images.githubusercontent.com/1134620/109079399-bef6c900-76b3-11eb-8125-029e1c715753.png">

Here's it not nested, still not right?
<img width="560" alt="Screen Shot 2021-02-24 at 3 17 19 PM" src="https://user-images.githubusercontent.com/1134620/109079406-c28a5000-76b3-11eb-9410-dc8a448fdf6d.png">

**Comment by argyleink** [comment]
still experiencing this. where should i look in the code to help it out?

**Comment by ryboe** [comment]
Sorry for the lack of response @argyleink 😬

[The `at-supports` syntax is specified here](https://github.com/ryboe/CSS3/blob/master/CSS3.sublime-syntax#L519). I did not test it very well, so I'm not surprised it's broken 🙁 

I honestly no longer have the motivation to maintain this package like I should. I no longer use Sublime Text as my main editor. Would you be interested in taking over as the maintainer? You've made some excellent contributions recently. I'm sure you would do a better job maintaining it than I have. I think my last contribution to this package will be migrating from CircleCI to GitHub Actions. Judging by [the SublimeText/UnitTesting README](https://github.com/SublimeText/UnitTesting), Actions seems to be the preferred was to run package tests.

**Comment by argyleink** [comment]
i'm cool with being a primary maintainer with you, but i also don't have any time to devote to this to give it a ton of love. 

i can give it more attention starting next year? i've got a heavy work load for the rest of 2021. 
i agree less folks use sublime text as their editor, which makes maintaining this not look as shiny. 

i could start with making supports work a bit more though, as a next task i take on?

**Comment by ryboe** [comment]
I've invited you to become a collaborator on this repo. That should grant you elevated permissions. Thanks very much! I really appreciate the contributions you've made. I think fixing `@supports` is a great next task. I'm sorry in advance for how complicated the nesting rules are. You have total authority to rip & tear wherever you see fit. If you see something that looks gnarly and you want to rip it out, rip it out 🙂

**Comment by ryboe** [comment]
I just released [v2.1.37](https://github.com/ryboe/CSS3/releases/tag/v2.1.37) which should make `@supports` highlighting much better. Please let me know (and provide code samples) if `@supports` is still broken.
