### ISSUE TITLE
Stray double quote in completions/functions.py

### ISSUE THREAD

**Issue by joreiff** [ryboe/CSS3#154]
There seems to be a stray double quote in `completions/functions.py` resulting in a `SyntaxError` being raised:

https://github.com/ryboe/CSS3/blob/f0696d67cbe09be6a704e8e166241e8aae56922d/completions/functions.py#L6-L8

**Comment by ryboe** [comment]
Thanks very much for identifying the problem, @joreiff! 🙏 The fixed release should land on Package Control within an hour.

**Comment by joreiff** [comment]
I can confirm, the exception is gone. Thank you!
