### ISSUE TITLE
How to turn off the annoying auto complete of this plugin?

### ISSUE THREAD

**Issue by ClassicOldSong** [ryboe/CSS3#160]
When I type some css and the completion list pop out, I hit tab, and I always get a result that's totally not what I wanted.

For example:

![image](https://user-images.githubusercontent.com/10512422/110361754-65ab7400-807b-11eb-9aab-4b66635a95db.png)

When I hit `tab`, it gives me `list-style: hei;`, not `line-height`.

Please give a solution to this problem.

**Comment by ryboe** [comment]
Hi, @ClassicOldSong. I'm not sure what's causing your issue. My best guess is that multiple plugins are competing to offer completions for CSS. I recommend disabling the default CSS plugin and Emmet completions when running CSS3. Check out steps 3, 4, and 5 of [the installation instructions](https://github.com/ryboe/CSS3#installation).

**Comment by ClassicOldSong** [comment]
I've disabled the built-in CSS plugin and still having the same issue. Will try disabling Emmet and see if it has any difference.

**Comment by ClassicOldSong** [comment]
Disabling emmet solves the problem. Thanks!

**Comment by ClassicOldSong** [comment]
Also the fifth step of the installation instruction isn't working anymore. Only disabling Emmet could solve the issue.

**Comment by ryboe** [comment]
Thanks for reporting that the completions clash with Emmet is happening again! I've opened [an issue to track the problem here](https://github.com/ryboe/CSS3/issues/161) and [an issue on the Emmet repo asking for help](https://github.com/emmetio/sublime-text-plugin/issues/157).
