### ISSUE TITLE
Issue: It seems autocompletion is not working in version v2.1.38

### ISSUE THREAD

**Issue by Jomange20** [ryboe/CSS3#174]
First let me thank your of this package, I really like it.

I have been working with CSS3 package for a couple of years, Suddenly auto complete was not working (noticed at 22 Nov 2021)
The autocomplete menu is not showing at all while typing even with ctrl+space it's not shown
After trying the following (I use sublime Text v 3.2.2 build 3211 on windows 10 updated to the latest)
1- remove/add the CSS3 package 
2- uninstall ST3 and install it again and add only the package control plus CSS3 and do all setting instructions including remove default CSS
3- do manual install to the CSS3 package

I had come up with the following after manually added CSS3 package folder to the  Roaming\Sublime Text 3\Packages\
- The version v2.1.35 is working fine as usual 
- The version v2.1.38 has no intellisense/auto complete is gone it seems it doesn't know any CSS selector, property or value at all.
- I had tried replacing them many times and still get the same results v2.1.35 but v2.1.38, I didn't try versions in between them.

For now I had to disable package auto_upgrade until this solved

Thank you for your time
Good luck

**Comment by ryboe** [comment]
Hmm, completions are working fine for me on ST4 build 4121 with the latest `master` commit. I wonder if this is an ST3 vs ST4 issue 🤔

I just released v2.1.39 which is at the latest `master` commit. Please let me know if completions are still broken for you. Thanks!

**Comment by ryboe** [comment]
I'm gonna close this because I haven't heard any new reports since v2.1.40 was released. Please reopen if you're still experiencing this.
