### ISSUE TITLE
Syntax colors without but with default autocompletition

### ISSUE THREAD

**Issue by Draghmar** [ryboe/CSS3#175]
Hi
Like in the title: is it possible? I really like all the touches to the CSS3 parts that default theme don't handle well but I've noticed that default autocompletitions work better. For example typing `bg` gives me `background: ǀ;` when tabbed, which is something I'd like to see and it also works with variables in `var` syntax.

**Comment by ryboe** [comment]
This bug _should be_ fixed in v2.1.40, but if you're still having issues, let's move this discussion to #174
