### ISSUE TITLE
`font`, `menu`, `backdrop-filter` not highlighting/including properly

### ISSUE THREAD

**Issue by ehzro3** [ryboe/CSS3#181]
I'm learning ST syntax definition to contribute but before I make any change I want to report problems according to the guideline.

# Problem

### Functional notation
<img width="212" alt="Screen Shot 2022-08-21 at 18 24 51" src="https://user-images.githubusercontent.com/40330010/185813446-da409f46-b583-4d13-9d52-fb118022428a.png">

### Keyword
<img width="188" alt="Screen Shot 2022-08-21 at 18 25 09" src="https://user-images.githubusercontent.com/40330010/185813444-457f4151-aa08-45d1-a243-60a40762c6ac.png">

## `backdrop-filter` is unmatched
<img width="197" alt="Screen Shot 2022-08-21 at 18 25 17" src="https://user-images.githubusercontent.com/40330010/185813443-a6959178-8fb9-4390-a208-845119384fa5.png">

## `menu` matches `invalid.deprecated.css`
- `menuitem` is deprecated but `menu` is not
<img width="199" alt="Screen Shot 2022-08-21 at 18 25 01" src="https://user-images.githubusercontent.com/40330010/185813445-9725541a-c9bc-4215-b009-2d91ec499e61.png">

**Comment by argyleink** [comment]
nice catches 👍🏻

**Comment by vrugtehagel** [comment]
PRs have been opened:
 - `font`: https://github.com/ryboe/CSS3/pull/192
 - `backdrop-filter`: https://github.com/ryboe/CSS3/pull/187
 - `menu`: https://github.com/ryboe/CSS3/pull/186
