### ISSUE TITLE
Add mathematical functions

### ISSUE THREAD

**Issue by vrugtehagel** [ryboe/CSS3#205]
It'd be nice to support the newer mathematical functions. Specifically:

- `round()`
- `mod()`
- `rem()`
- `sin()`
- `cos()`
- `tan()`
- `asin()`
- `acos()`
- `atan()`
- `atan2()`
- `pow()`
- `sqrt()`
- `hypot()`
- `log()`
- `exp()`
- `abs()`
- `sign()`

See the section on [Math functions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#math_functions) on MDN.

**Comment by argyleink** [comment]
fixed by #218
