### ISSUE TITLE
The problem with autocomplete

### ISSUE THREAD

**Issue by APEXRARE2009** [ryboe/CSS3#216]
Autocomplete перестал работать в последнем версии sublime text, исправте пожалуйста.

Заранее спасибо

**Comment by APEXRARE2009** [comment]
Hello,

Autofill has stopped working in the latest version of Sublime Text, please fix it.

Thank you in advance.

**Comment by argyleink** [comment]
will investigate asap

**Comment by APEXRARE2009** [comment]
Thank you very much😄

**Comment by APEXRARE2009** [comment]
Hello,
is there any news?

**Comment by Luuk-van-Aggelen** [comment]
Following..

**Comment by argyleink** [comment]
duplicate of https://github.com/ryboe/CSS3/issues/198

**Comment by Luuk-van-Aggelen** [comment]
I'm not entirely sure how this links to an issue from a year ago. This always worked perfectly up until last week.

**Comment by emilezeldenrust** [comment]
I am also experiencing this problem. Since last week there is something wrong with autocomplete. The colon and semicolon do not appear when you press tab.

**Comment by APEXRARE2009** [comment]
The problem remains

**Comment by argyleink** [comment]
nothin suspicious looking in the latest release that leads towards autocomplete issues https://github.com/ryboe/CSS3/compare/v2.1.43...master
